### ISSUE TITLE
Invalid memory address

### ISSUE THREAD

**Issue by kpetremann** [kpetremann/salt-exporter#55]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x546d68]

goroutine 3763 [running]:
github.com/charmbracelet/bubbles/list.filterItems.func1()
        /home/runner/go/pkg/mod/github.com/charmbracelet/bubbles@v0.16.1/list/list.go:1211 +0x1a8
github.com/charmbracelet/bubbletea.(*Program).handleCommands.func1.1()
        /home/runner/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.24.2/tea.go:268 +0x38
created by github.com/charmbracelet/bubbletea.(*Program).handleCommands.func1
        /home/runner/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.24.2/tea.go:267 +0x14d

**Comment by kpetremann** [comment]
same with 0.17.1

**Comment by kpetremann** [comment]
it is coming from RemoveItem: https://github.com/kpetremann/salt-exporter/blob/main/internal/tui/tui.go#L171C5-L171C49
No issue without it.
